[supervisord]
nodaemon=true
user=root

[program:fastapi]
command=uvicorn app.main:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true
priority=1

[program:celery]
command=celery -A app.worker.tasks worker --loglevel=info --pool=solo
autostart=true
autorestart=true
priority=2
