"""add user llm config

Revision ID: 083856111043
Revises: d512a3fe455d
Create Date: 2026-05-10 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083856111043'
down_revision: Union[str, None] = 'd512a3fe455d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('llm_api_key_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('llm_base_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('llm_model', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('llm_config_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'llm_config_updated_at')
    op.drop_column('users', 'llm_model')
    op.drop_column('users', 'llm_base_url')
    op.drop_column('users', 'llm_api_key_encrypted')
    # ### end Alembic commands ###
