"""add actual_summary_json to Chapter

Revision ID: 3bae85f20ef6
Revises: f210059ee189
Create Date: 2026-08-05 16:17:27.656253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bae85f20ef6'
down_revision: Union[str, None] = 'f210059ee189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('actual_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'actual_summary_json')
    # ### end Alembic commands ###
