"""add hot topics table

Revision ID: 81909d23eb6a
Revises: 083856111043
Create Date: 2026-08-04 14:25:25.174855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81909d23eb6a'
down_revision: Union[str, None] = '083856111043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hot_topics',
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('note_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('collects', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', name='uq_hot_topics_note_id')
    )
    op.create_index(op.f('ix_hot_topics_category'), 'hot_topics', ['category'], unique=False)
    op.create_index(op.f('ix_hot_topics_fetched_at'), 'hot_topics', ['fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hot_topics_fetched_at'), table_name='hot_topics')
    op.drop_index(op.f('ix_hot_topics_category'), table_name='hot_topics')
    op.drop_table('hot_topics')
    # ### end Alembic commands ###
