"""add_drama_episodes_table

Revision ID: 8a79b9d90021
Revises: 5e3a33577bdd
Create Date: 2026-05-05 22:29:53.646076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a79b9d90021'
down_revision: Union[str, None] = '5e3a33577bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drama_episodes',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('episode_num', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('source_chapters', sa.String(length=255), nullable=True),
    sa.Column('outline_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('script_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drama_episodes')
    # ### end Alembic commands ###
