"""add inspiration curation columns

Revision ID: d8c4a212986c
Revises: 81909d23eb6a
Create Date: 2026-08-05 07:26:53.254861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c4a212986c'
down_revision: Union[str, None] = '81909d23eb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows so NOT NULL columns can be added;
    # defaults are then dropped to match the model (client-side defaults only).
    op.add_column('hot_topics', sa.Column('comment_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('hot_topics', sa.Column('inspiration_hint', sa.Text(), nullable=True))
    op.add_column('hot_topics', sa.Column('quality_score', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('hot_topics', sa.Column('rank_score', sa.Float(), nullable=False, server_default='0'))
    op.alter_column('hot_topics', 'comment_count', server_default=None)
    op.alter_column('hot_topics', 'quality_score', server_default=None)
    op.alter_column('hot_topics', 'rank_score', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hot_topics', 'rank_score')
    op.drop_column('hot_topics', 'quality_score')
    op.drop_column('hot_topics', 'inspiration_hint')
    op.drop_column('hot_topics', 'comment_count')
    # ### end Alembic commands ###
